#!/bin/bash
set -e

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
    CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
    GRANT SELECT,INSERT,UPDATE,DELETE ON \`${MYSQL_DATABASE}\`.* TO '${DB_USER}'@'%';
    FLUSH PRIVILEGES;
EOSQL
